-- transactions.sql removed — project no longer uses a separate `transactions` table.
-- Payment records are stored in the `payments` table. The database used by the running application
-- has been adjusted accordingly and the transactions table was deleted from the database.
